### ISSUE TITLE
Add support for CIDR based networks

### ISSUE THREAD

**Issue by arg2009** [diegonz/PHPWakeOnLan#10]
### Info:

- PHPWakeOnLan version: 2.1.1
- PHP version: 8.2.17
- Operative system: Linux
- Execution environment: Web and CLI

### Description:

The current implementation of PHPWakeOnLan only allows sending magic packets to broadcast addresses that end in `.255`. This is due to the validation check of the broadcast address property that enforces this.
https://github.com/diegonz/PHPWakeOnLan/blob/9aa39ab768f02acab0ffa0dc47a6e9cc0c81013d/src/PHPWakeOnLan.php#L69

[CIDR](https://en.wikipedia.org/wiki/Classless_Inter-Domain_Routing) based networks do not have this restriction and can frequently have a network broadcast address that does not end in `255`. Such an example would be the network `192.168.50.0/28`:

```
Network Address: 192.168.50.0
Broadcast Address: 192.168.50.15
Number of addresses: 16
Subnet Mask: 255.255.255.240
```

With the current implementation, hosts on this network would only be able to receive magic packets sent to the global broadcast address `255.255.255.255` meaning the magic packet would be send to all hosts on all subnets within the router's border.

CIDR based broadcasting would provide more efficient magic packet routing.

### Pull Request

I have implement CIDR based broadcasting while maintaining backwards compatibility with the existing `wake` function.

https://github.com/diegonz/PHPWakeOnLan/pull/11

**Comment by diegonz** [comment]
Thanks, I appreciate your contribution. Your PR is merged now.
